version: '3.9'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules

services:
  time2blocks-ngx-dev:
    image: time2blocks-ngx-dev
    container_name: time2blocks-ngx-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /time2blocks-ngx
    ports:
      - "4200:4200"
      - "9876:9876"
    volumes:
      - ..:/time2blocks-ngx:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules_vol:/time2blocks-ngx/node_modules
    tty: true
