version: '3.9'

services:
  time2blocks-ngx-dev:
    image: time2blocks-ngx-dev
    container_name: time2blocks-ngx-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /time2blocks-ngx
    ports:
      - "4203:4200"
      - "9876:9876"
    volumes:
      - ..:/time2blocks-ngx:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
